/* GENERAT PER CHATGPT */
INSERT INTO COUNTRYS (flag, name, created_at, updated_at, deleted_at)
VALUES
    ('AF', 'Afganistán', NOW(), NOW(), NULL),
    ('AL', 'Albania', NOW(), NOW(), NULL),
    ('DZ', 'Argelia', NOW(), NOW(), NULL),
    ('AD', 'Andorra', NOW(), NOW(), NULL),
    ('AO', 'Angola', NOW(), NOW(), NULL),
    ('AR', 'Argentina', NOW(), NOW(), NULL),
    ('AM', 'Armenia', NOW(), NOW(), NULL),
    ('AU', 'Australia', NOW(), NOW(), NULL),
    ('AT', 'Austria', NOW(), NOW(), NULL),
    ('AZ', 'Azerbaiyán', NOW(), NOW(), NULL),
    ('BS', 'Bahamas', NOW(), NOW(), NULL),
    ('BH', 'Baréin', NOW(), NOW(), NULL),
    ('BD', 'Bangladés', NOW(), NOW(), NULL),
    ('BB', 'Barbados', NOW(), NOW(), NULL),
    ('BY', 'Bielorrusia', NOW(), NOW(), NULL),
    ('BE', 'Bélgica', NOW(), NOW(), NULL),
    ('BZ', 'Belice', NOW(), NOW(), NULL),
    ('BJ', 'Benín', NOW(), NOW(), NULL),
    ('BT', 'Bután', NOW(), NOW(), NULL),
    ('BO', 'Bolivia', NOW(), NOW(), NULL),
    ('BA', 'Bosnia y Herzegovina', NOW(), NOW(), NULL),
    ('BW', 'Botsuana', NOW(), NOW(), NULL),
    ('BR', 'Brasil', NOW(), NOW(), NULL),
    ('BN', 'Brunéi', NOW(), NOW(), NULL),
    ('BG', 'Bulgaria', NOW(), NOW(), NULL),
    ('BF', 'Burkina Faso', NOW(), NOW(), NULL),
    ('BI', 'Burundi', NOW(), NOW(), NULL),
    ('KH', 'Camboya', NOW(), NOW(), NULL),
    ('CM', 'Camerún', NOW(), NOW(), NULL),
    ('CA', 'Canadá', NOW(), NOW(), NULL),
    ('CV', 'Cabo Verde', NOW(), NOW(), NULL),
    ('CF', 'República Centroafricana', NOW(), NOW(), NULL),
    ('TD', 'Chad', NOW(), NOW(), NULL),
    ('CL', 'Chile', NOW(), NOW(), NULL),
    ('CN', 'China', NOW(), NOW(), NULL),
    ('CO', 'Colombia', NOW(), NOW(), NULL),
    ('KM', 'Comoras', NOW(), NOW(), NULL),
    ('CG', 'Congo', NOW(), NOW(), NULL),
    ('CR', 'Costa Rica', NOW(), NOW(), NULL),
    ('HR', 'Croacia', NOW(), NOW(), NULL),
    ('CU', 'Cuba', NOW(), NOW(), NULL),
    ('CY', 'Chipre', NOW(), NOW(), NULL),
    ('CZ', 'República Checa', NOW(), NOW(), NULL),
    ('DK', 'Dinamarca', NOW(), NOW(), NULL),
    ('DJ', 'Yibuti', NOW(), NOW(), NULL),
    ('DO', 'República Dominicana', NOW(), NOW(), NULL),
    ('EC', 'Ecuador', NOW(), NOW(), NULL),
    ('EG', 'Egipto', NOW(), NOW(), NULL),
    ('SV', 'El Salvador', NOW(), NOW(), NULL),
    ('GQ', 'Guinea Ecuatorial', NOW(), NOW(), NULL),
    ('ER', 'Eritrea', NOW(), NOW(), NULL),
    ('EE', 'Estonia', NOW(), NOW(), NULL),
    ('ET', 'Etiopía', NOW(), NOW(), NULL),
    ('FJ', 'Fiyi', NOW(), NOW(), NULL),
    ('FI', 'Finlandia', NOW(), NOW(), NULL),
    ('FR', 'Francia', NOW(), NOW(), NULL),
    ('GA', 'Gabón', NOW(), NOW(), NULL),
    ('GM', 'Gambia', NOW(), NOW(), NULL),
    ('GE', 'Georgia', NOW(), NOW(), NULL),
    ('DE', 'Alemania', NOW(), NOW(), NULL),
    ('GH', 'Ghana', NOW(), NOW(), NULL),
    ('GR', 'Grecia', NOW(), NOW(), NULL),
    ('GT', 'Guatemala', NOW(), NOW(), NULL),
    ('GN', 'Guinea', NOW(), NOW(), NULL),
    ('HT', 'Haití', NOW(), NOW(), NULL),
    ('HN', 'Honduras', NOW(), NOW(), NULL),
    ('HU', 'Hungría', NOW(), NOW(), NULL),
    ('IS', 'Islandia', NOW(), NOW(), NULL),
    ('IN', 'India', NOW(), NOW(), NULL),
    ('ID', 'Indonesia', NOW(), NOW(), NULL),
    ('IR', 'Irán', NOW(), NOW(), NULL),
    ('IQ', 'Irak', NOW(), NOW(), NULL),
    ('IE', 'Irlanda', NOW(), NOW(), NULL),
    ('IL', 'Israel', NOW(), NOW(), NULL),
    ('IT', 'Italia', NOW(), NOW(), NULL),
    ('JP', 'Japón', NOW(), NOW(), NULL),
    ('JO', 'Jordania', NOW(), NOW(), NULL),
    ('KZ', 'Kazajistán', NOW(), NOW(), NULL),
    ('KE', 'Kenia', NOW(), NOW(), NULL),
    ('KR', 'Corea del Sur', NOW(), NOW(), NULL),
    ('KW', 'Kuwait', NOW(), NOW(), NULL),
    ('LV', 'Letonia', NOW(), NOW(), NULL),
    ('LB', 'Líbano', NOW(), NOW(), NULL),
    ('LY', 'Libia', NOW(), NOW(), NULL),
    ('LT', 'Lituania', NOW(), NOW(), NULL),
    ('LU', 'Luxemburgo', NOW(), NOW(), NULL),
    ('MG', 'Madagascar', NOW(), NOW(), NULL),
    ('MY', 'Malasia', NOW(), NOW(), NULL),
    ('MX', 'México', NOW(), NOW(), NULL),
    ('MA', 'Marruecos', NOW(), NOW(), NULL),
    ('NP', 'Nepal', NOW(), NOW(), NULL),
    ('NL', 'Países Bajos', NOW(), NOW(), NULL),
    ('NZ', 'Nueva Zelanda', NOW(), NOW(), NULL),
    ('NI', 'Nicaragua', NOW(), NOW(), NULL),
    ('NG', 'Nigeria', NOW(), NOW(), NULL),
    ('NO', 'Noruega', NOW(), NOW(), NULL),
    ('PK', 'Pakistán', NOW(), NOW(), NULL),
    ('PE', 'Perú', NOW(), NOW(), NULL),
    ('PH', 'Filipinas', NOW(), NOW(), NULL),
    ('PT', 'Portugal', NOW(), NOW(), NULL),
    ('RU', 'Rusia', NOW(), NOW(), NULL),
    ('ES', 'España', NOW(), NOW(), NULL),
    ('SE', 'Suecia', NOW(), NOW(), NULL),
    ('CH', 'Suiza', NOW(), NOW(), NULL),
    ('UA', 'Ucrania', NOW(), NOW(), NULL),
    ('GB', 'Reino Unido', NOW(), NOW(), NULL),
    ('US', 'Estados Unidos', NOW(), NOW(), NULL);