networks:
  bitacora_forum_network:
    ipam:
      config:
        - subnet: 172.21.0.0/16

services:

  db:
    container_name: mysql-db
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    env_file:
      - ./conf/mysql.env
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      bitacora_forum_network:
        ipv4_address: 172.21.0.10

  api:
    container_name: fiber-api
    build: ./api/
    ports:
      - 8080:8080
    env_file:
      - ./conf/api.env
    volumes:
      - ./api/:/go/src/app
    depends_on:
      - db
    networks:
      bitacora_forum_network:
        ipv4_address: 172.21.0.12

  client:
    container_name: nuxt-client
    build: ./client/
    ports:
      - '3000:3000'
    volumes:
      - './client:/opt/app'
    depends_on:
      - api
    networks:
      bitacora_forum_network:
        ipv4_address: 172.21.0.13    

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8005:80
    env_file:
      - ./conf/phpmyadmin.env
    depends_on:
      - db
    networks:
      bitacora_forum_network:
        ipv4_address: 172.21.0.11