networks:
  vnetwork:
    ipam:
      config:
        - subnet: 172.21.0.0/16

services:

  db:
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    env_file:
      - ./conf/mysql.env
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      vnetwork:
        ipv4_address: 172.21.0.10

  api:
    build: ./api/
    ports:
      - 8080:8080
    env_file:
      - ./conf/api.env
    volumes:
      - ./api/:/go/src/app
    depends_on:
      - db
    networks:
      vnetwork:
        ipv4_address: 172.21.0.12

  client:
    image: node:23-alpine3.20
    ports:
      - '5173:5173'
    volumes:
      - './client:/opt/app'
    networks:
      vnetwork:
        ipv4_address: 172.21.0.13
    working_dir: /opt/app
    command: npx vite --host=0.0.0.0
    

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8005:80
    env_file:
      - ./conf/phpmyadmin.env
    depends_on:
      - db
    networks:
      vnetwork:
        ipv4_address: 172.21.0.11